// The single country table for the whole app.
//
// Generated by scripts/generate-countries.js. Every code mapping the app needs -
// ISO2, ISO3, and the CIA GEC code - lives on one record, alongside flags saying
// which datasets actually cover that country. Previously four separate hand-written
// maps disagreed with each other and with the dropdown.

import countriesData from '../data/countries.json';

export interface CountryCoverage {
  /** World Bank Open Data - accepts ISO2 directly, so this is always true. */
  worldBank: boolean;
  /** CIA World Factbook mirror - needs a GEC code, which not every country has. */
  factbook: boolean;
  /** UNODC crime statistics - keyed by ISO3, published for ~170 countries. */
  crime: boolean;
}

export interface Country {
  /** ISO 3166-1 alpha-2. The app's primary key for a country. */
  code: string;
  /** ISO 3166-1 alpha-3, used by the climate and crime datasets. */
  iso3: string;
  name: string;
  officialName: string;
  flag: string;
  region: string | null;
  subregion: string | null;
  capital: string[];
  currencies: Record<string, { name: string; symbol: string }>;
  languages: Record<string, string>;
  /** Distinct UTC offsets, e.g. ["UTC-05:00", "UTC-06:00"]. */
  timezones: string[];
  googleMaps: string | null;
  /** CIA GEC code; null when the Factbook has no entry for this country. */
  gec: string | null;
  coverage: CountryCoverage;
}

// Cast through unknown: TypeScript infers a union of literal object types from the
// JSON import, which never structurally matches the interface even though the
// generator guarantees the shape.
export const countries: Country[] = countriesData as unknown as Country[];

const byCode = new Map(countries.map((c) => [c.code, c]));
const byIso3 = new Map(countries.map((c) => [c.iso3, c]));

/** Look up a country by ISO2 code (case-insensitive). */
export function getCountry(code: string | null | undefined): Country | undefined {
  if (!code) return undefined;
  return byCode.get(code.toUpperCase());
}

/**
 * Resolve any supported code to ISO3.
 *
 * Accepts an ISO2 code, or an ISO3 code passed straight through, so callers do not
 * have to know which form they were handed.
 */
export function toIso3(code: string | null | undefined): string | undefined {
  if (!code) return undefined;
  const upper = code.toUpperCase();
  return byCode.get(upper)?.iso3 ?? (byIso3.has(upper) ? upper : undefined);
}

/** Resolve an ISO2 code to the CIA GEC code the Factbook mirror is keyed by. */
export function toGec(code: string | null | undefined): string | undefined {
  return getCountry(code)?.gec ?? undefined;
}

/** True when the named dataset publishes figures for this country. */
export function hasCoverage(
  code: string | null | undefined,
  dataset: keyof CountryCoverage
): boolean {
  return getCountry(code)?.coverage[dataset] ?? false;
}
